version: "3.8"
services:
  game:
    build: .
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/dri:/dev/dri"  # Để hỗ trợ phần cứng GPU (nếu có)
    stdin_open: true
    tty: true
