# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_over.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(100, 20, 200, 40))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setStyleSheet("font-size: 24px; color: red;")
        self.label_title.setObjectName("label_title")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(100, 80, 200, 30))
        self.label_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score.setObjectName("label_score")
        self.label_high_score = QtWidgets.QLabel(self.centralwidget)
        self.label_high_score.setGeometry(QtCore.QRect(100, 120, 200, 30))
        self.label_high_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_high_score.setObjectName("label_high_score")
        self.btn_try_again = QtWidgets.QPushButton(self.centralwidget)
        self.btn_try_again.setGeometry(QtCore.QRect(100, 170, 200, 40))
        self.btn_try_again.setObjectName("btn_try_again")
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(100, 220, 200, 40))
        self.btn_quit.setObjectName("btn_quit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game Over"))
        self.label_title.setText(_translate("MainWindow", "GAME OVER"))
        self.label_score.setText(_translate("MainWindow", "Your Score: 0"))
        self.label_high_score.setText(_translate("MainWindow", "High Score: 0"))
        self.btn_try_again.setText(_translate("MainWindow", "Try Again"))
        self.btn_quit.setText(_translate("MainWindow", "Quit"))
